[package]
name = "ufs-dump"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
env_logger.workspace = true
libc.workspace = true
log.workspace = true
rufs.workspace = true
